"use client";
import { FormEvent, useState } from "react";
import { site } from "@/lib/site";

export default function Contact(){
 const [intent,setIntent]=useState("Hiring / Job"),[status,setStatus]=useState(""),[errors,setErrors]=useState<Record<string,string>>({}),[copied,setCopied]=useState("");
 async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);setCopied(label);setTimeout(()=>setCopied(""),1500)}catch{}}
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();const form=e.currentTarget,data=new FormData(form),name=String(data.get("name")||"").trim(),email=String(data.get("email")||"").trim(),message=String(data.get("message")||"").trim(),website=String(data.get("website")||"");
  if(website)return;const next:Record<string,string>={};if(!name)next.name="Enter your name.";if(!/^\S+@\S+\.\S+$/.test(email))next.email="Enter a valid email address.";if(message.length<20)next.message="Please use at least 20 characters.";setErrors(next);if(Object.keys(next).length)return;
  setStatus("Sending message…");try{const r=await fetch(`https://formspree.io/f/${site.formspreeId}`,{method:"POST",body:data,headers:{Accept:"application/json"}});if(!r.ok)throw new Error();form.reset();setStatus("Message sent. I’ll reply within 24 hours.")}catch{setStatus("Message could not be sent. Please email me directly.")}
 }
 const cards=[["Email",site.email,`mailto:${site.email}?subject=Opportunity%20for%20Chintala%20Mahindra`],["Phone",site.phone,`tel:${site.phone.replaceAll(" ","")}`],["LinkedIn",site.linkedin.replace("https://",""),site.linkedin],["Location",site.location,"#contact"]];
 return <section id="contact" className="contact-section" aria-labelledby="contact-title">
  <div className="contact-grid"><div><p className="eyebrow">Contact</p><h2 id="contact-title">Have a Java backend problem to solve?</h2><p className="contact-copy">Open to Java backend roles, AI-enabled backend projects and selected freelance work.</p>
   <div className="contact-cards">{cards.map(([label,value,href])=><div className="contact-card" key={label}><a href={href} target={label==="LinkedIn"?"_blank":undefined} rel={label==="LinkedIn"?"noreferrer":undefined}><strong>{label}</strong><span>{value}</span></a>{label!=="Location"&&<><button type="button" onClick={()=>copy(value,label)} aria-label={"Copy "+label}>Copy</button>{copied===label&&<em>Copied ✓</em>}</>}</div>)}</div>
  </div><div className="contact-form-wrap">{site.formspreeId?<form onSubmit={submit} noValidate><p className="form-kicker">Message intent</p><div className="intent-row">{["Hiring / Job","Freelance project","Just saying hi"].map(x=><button type="button" key={x} className={intent===x?"active":""} onClick={()=>setIntent(x)}>{x}</button>)}</div><input type="hidden" name="subject" value={intent+" | Chintala Mahindra"}/><label htmlFor="name">Name</label><input id="name" name="name" autoComplete="name" aria-invalid={!!errors.name}/>{errors.name&&<small>{errors.name}</small>}<label htmlFor="email">Email</label><input id="email" name="email" type="email" autoComplete="email" aria-invalid={!!errors.email}/>{errors.email&&<small>{errors.email}</small>}<label htmlFor="message">Message</label><textarea id="message" name="message" minLength={20} aria-invalid={!!errors.message}/>{errors.message&&<small>{errors.message}</small>}<div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1}/></div><button className="send-button" type="submit">{status.startsWith("Sending")?"Sending message…":"Send message"}</button><p className="form-status" aria-live="polite">{status}</p></form>:<div><p className="form-kicker">Prefer email?</p><p className="contact-copy">It’s the fastest.</p><a className="send-button" href={`mailto:${site.email}`}>Email Mahindra</a></div>}</div></div>
  <div className="mobile-contact-bar"><a href={`tel:${site.phone.replaceAll(" ","")}`}>Call</a><a href={`mailto:${site.email}`}>Email</a><a href={site.linkedin} target="_blank" rel="noreferrer">LinkedIn</a></div>
 </section>
}
