"use client";
import { useEffect, useState } from "react";
import Network from "./Network";
import Architecture from "./Architecture";
import RagLab from "./RagLab";
import Constellation from "./Constellation";
import Contact from "./Contact";
import { site, type Project } from "@/lib/site";

function Flow({project}:{project:Project}){
 const labels=project.name.startsWith("Digital")?["Client","API / Security","Service","PostgreSQL / Redis"]:project.name.startsWith("Policy")?["Ingest","Embed","pgvector","Retrieve","LLM"]:["Client","Spring Security","AI Orchestrator","Retrieval","Structured Response"];
 return <div className="project-flow">{labels.map((x,i)=><div key={x} className="project-flow-step"><span>{x}</span>{i<labels.length-1&&<i aria-hidden="true"/>}</div>)}</div>;
}
const nav=[["Work","#work"],["Experience","#experience"],["AI Lab","#ai-lab"],["Stack","#stack"],["Playground","#playground"],["Timeline","#timeline"],["Contact","#contact"]];
export default function Portfolio(){
 const [menu,setMenu]=useState(false),[scroll,setScroll]=useState(0);
 useEffect(()=>{const f=()=>setScroll(window.scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)*100);addEventListener("scroll",f,{passive:true});f();return()=>removeEventListener("scroll",f)},[]);
 return <>
  <div className="scroll-progress" style={{width:scroll+"%"}} aria-hidden="true"/>
  <header className="site-header"><nav className="nav-shell" aria-label="Primary navigation"><a className="brand" href="#top">CM / JAVA</a><div className="desktop-nav">{nav.map(([n,h])=><a key={n} href={h}>{n}</a>)}</div><a className="nav-contact" href="#contact">Contact</a><button className="menu-button" aria-expanded={menu} aria-label="Open navigation" onClick={()=>setMenu(!menu)}><span/><span/><span/></button></nav>{menu&&<div className="mobile-menu"><div>{nav.map(([n,h])=><a key={n} href={h} onClick={()=>setMenu(false)}>{n}</a>)}</div></div>}</header>
  <main id="main-content">
   <section id="top" className="hero-section"><div className="hero-grid"><div><p className="eyebrow">Java backend engineering · Hyderabad</p><h1>Chintala Mahindra</h1><p className="hero-role">Java Backend Engineer</p><p className="hero-copy">Building secure Spring Boot systems, distributed backend services and practical AI applications.</p><div className="hero-actions"><a className="action-primary" href={`mailto:${site.email}?subject=Opportunity%20for%20Chintala%20Mahindra`}>Email Mahindra</a><a className="action-secondary" href={site.resume} download>Download resume (PDF)</a></div><p className="availability-copy">Open to Java backend roles, AI-enabled backend projects and freelance work. Hyderabad. {site.responseTime}.</p></div><Network/></div></section>
   <section id="about" className="open-section"><div className="two-column"><div><p className="eyebrow">Engineering focus</p><h2>Backend systems first. AI where it fits.</h2></div><div><p>Java backend engineering is the center of gravity: APIs, persistence, security, messaging, caching and cloud delivery. AI is layered into that foundation through practical application patterns such as retrieval, embeddings and controlled LLM access.</p><div className="skill-table">{[["Backend","Java 21 · Spring Boot 3 · REST · JPA / Hibernate"],["Distributed","Kafka · Redis · AWS · Docker · CI/CD"],["AI applications","Spring AI · RAG · Embeddings · Vector Search · pgvector"]].map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></div></div></section>
   <section id="work" className="work-section"><div className="section-heading"><p className="eyebrow">Selected work</p><h2>Projects built around real backend problems.</h2></div><div className="project-grid">{site.projects.map(p=><article className="project-sheet" key={p.name}><div className="project-head"><div><span className="status">{p.status}</span><h3>{p.name}</h3><p>{p.role}, {p.period}</p></div></div><p className="problem">{p.problem}</p><div className="project-columns"><div><h4>What I built</h4><ul>{p.built.map(x=><li key={x}>{x}</li>)}</ul></div><div><h4>Key decisions</h4><ul>{p.decisions.map(x=><li key={x}>{x}</li>)}</ul></div></div><div className="tags">{p.stack.map(x=><span key={x}>{x}</span>)}</div><Flow project={p}/>{(p.github||p.live)&&<div className="project-links">{p.github&&<a href={p.github}>Open on GitHub</a>}{p.live&&<a href={p.live}>Open live demo</a>}</div>}</article>)}</div></section>
   <section id="experience" className="open-section"><div className="two-column"><div><p className="eyebrow">Professional experience</p><h2>Tata Consultancy Services</h2><p className="role-meta">Software Engineer — Java Backend, Aug 2024 — Present, Hyderabad</p></div><div className="experience-list">{[["Backend","Spring Boot 3 microservices on Java 21; REST APIs and Spring Data JPA across PostgreSQL / SQL Server."],["Security","Spring Security with JWT authentication and role-based access control across employee, HR and administrative endpoints."],["Messaging & caching","Apache Kafka for asynchronous event processing and Redis caching for high-frequency payroll and attendance lookups."],["AI integration","Spring AI integration for document- and policy-based Q&A using retrieval and embeddings, with application-level access controls applied to retrieved context."],["Operations","Production debugging, API and database issue resolution, and ongoing enhancements across backend services in Agile delivery."]].map(([a,b])=><div key={a}><strong>{a}</strong><p>{b}</p></div>)}</div></div></section>
   <section id="ai-lab" className="blueprint-section"><div className="section-heading"><p className="eyebrow">AI application engineering</p><h2>Retrieval before generation.</h2><p>AI capabilities stay inside the backend boundary. Authorization determines the data scope; retrieval assembles the context; the model generates from that context.</p></div><RagLab/></section>
   <section id="stack" className="open-section"><div className="section-heading"><p className="eyebrow">Engineering stack</p><h2>The systems around the core.</h2></div><Constellation/></section>
   <section id="playground" className="blueprint-section"><div className="section-heading"><p className="eyebrow">Architecture playground</p><h2>Think in systems.</h2></div><Architecture/></section>
   <section id="timeline" className="open-section"><div className="section-heading"><p className="eyebrow">Timeline</p><h2>Work and builds over time.</h2></div><div className="timeline">{[["2024","TCS / Java Backend","Enterprise HRMS & Finance Microservices"],["2025","Digital Library","Spring Boot backend platform"],["Present","PolicyDocs","Spring AI, RAG, embeddings, pgvector and controlled retrieval"]].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><p>{x[2]}</p></div>)}</div></section>
   <Contact/>
  </main>
  <footer><div><span>{site.name} | {site.role} | Hyderabad</span><a href={`mailto:${site.email}`}>{site.email}</a><a href={site.linkedin} target="_blank" rel="noreferrer">LinkedIn</a><a href="#top">Back to top</a><span>© {new Date().getFullYear()}</span></div></footer>
 </>;
}
